### ISSUE TITLE
Does not work with Zod 3.25

### ISSUE THREAD

**Issue by kingbri1** [samchungy/zod-openapi#447]
Runtime: Deno 2.3.3
Zod version: 3.25.3
Zod-openapi version: 4.24

Hi there, I recently tried updating Zod to version 3.25 and I get an error that openapi doesn't exist despite importing the extend script.

```
import "zod-openapi/extend";
import { z } from "zod";

const HelloSchema = z.object({
    testNum: z.number().openapi({ description: "test number" })
});
```

Error from TS: `Property 'openapi' does not exist on type 'ZodNumber'`

NOTE: I am not using zod 4 in this example.

**Comment by samchungy** [comment]
You've likely got conflicting versions of `zod`. Check your lockfile

**Comment by kingbri1** [comment]
Yep, you're right! This was due to Deno's lock file not updating. I just removed it and re-ran deno install. Closing.
